//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session3Api.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KazanNeftSession3DBEntities : DbContext
    {
        public KazanNeftSession3DBEntities()
            : base("name=KazanNeftSession3DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetOdometers> AssetOdometers { get; set; }
        public virtual DbSet<Assets> Assets { get; set; }
        public virtual DbSet<PMScheduleModels> PMScheduleModels { get; set; }
        public virtual DbSet<PMScheduleTypes> PMScheduleTypes { get; set; }
        public virtual DbSet<PMTasks> PMTasks { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
    }
}
